NAME = braiiiiiiinnnzzzz

all:	$(NAME)

$(NAME):
	c++ -Wall -Wextra -Werror -std=c++98 Zombie.cpp newZombie.cpp randomChump.cpp main.cpp -o $(NAME)

fclean:
	rm $(NAME)

re: fclean all

.PHONY: all fclean re
